'''
Created on Oct 24, 2012

@author: william

This auxiliar file, defines a set of common labels used to plot stuff
'''

prop_labels = { 'A_V':'$A_V$',
                'at_flux':'$\\langle \log t_\star \\rangle_L$',
                'am_flux':'$< \log Z_\star >_L$',
                'at_mass':'$\\langle \log t_\star \\rangle_M$',
                'am_mass':'$< \log Z_\star >_M$',
                'M2L_r':'$ \log M / L_r$',
                'Mcor_gal':'$\log M_\star$',
                'EW_3727':'$\log W_{ [ O II ] }$', #  [\AA^{-1}]
                'EW_4861':'$\log W_{H\\beta}$',
                'EW_5007':'$\log W_{ [ O III ] }$',
                'EW_6563':'$\log W_{H\\alpha}$',
                'EW_6584':'$\log W_{[ \\rm{N} II ]}$',
                'Ha':'$H_\\alpha$',
                'N2Ha':'$\log [ N II ] / H_\\alpha$',
                'O3Hb':'$\log [ O III ] / H_\\beta$',
                'HaHb':'$\log H_\\alpha / H_\\beta$',
                'S2Ha':'$\log [ S II ] / H_\\alpha$',
                'O2Hb':'$\log [ O II ] / H_\\beta$',
                'O3N2':'$\log [ O III ]/ [ N II ]$' }

prop_minmax = { 'AV': (-1.0, 2.0),
                'at_flux': (6.0, 10.5),
                'am_flux': (0.0, 2.5),
                'at_mass': (6.0, 10.5),
                'am_mass': (0.0, 2.5),
                'M2Lcor': (0.0, 6.5) }

aux_name_props = {'F_3727': {'log': True, 'eval': False},
                 'EW_3727': {'log': True, 'eval': False},
                 'F_3869': {'log': True, 'eval': False},
                 'EW_3869': {'log': True, 'eval': False},
                 'F_4101': {'log': True, 'eval': False},
                 'EW_4101': {'log': True, 'eval': False},
                 'F_4340': {'log': True, 'eval': False},
                 'EW_4340': {'log': True, 'eval': False},
                 'F_4363': {'log': True, 'eval': False},
                 'EW_4363': {'log': True, 'eval': False},
                 'F_4861': {'log': True, 'eval': False},
                 'EW_4861': {'log': True, 'eval': False},
                 'F_4959': {'log': True, 'eval': False},
                 'EW_4959': {'log': True, 'eval': False},
                 'F_5007': {'log': True, 'eval': False},
                 'EW_5007': {'log': True, 'eval': False},
                 'F_6300': {'log': True, 'eval': False},
                 'EW_6300': {'log': True, 'eval': False},
                 'F_6548': {'log': True, 'eval': False},
                 'EW_6548': {'log': True, 'eval': False},
                 'F_6563': {'log': True, 'eval': False},
                 'EW_6563': {'log': True, 'eval': False},
                 'F_6584': {'log': True, 'eval': False},
                 'EW_6584': {'log': True, 'eval': False},
                 'F_6717': {'log': True, 'eval': False},
                 'EW_6717': {'log': True, 'eval': False},
                 'F_6731': {'log': True, 'eval': False},
                 'EW_6731': {'log': True, 'eval': False},
                 'F_4471': {'log': True, 'eval': False},
                 'EW_4471': {'log': True, 'eval': False},
                 'A_V': {'log': False, 'eval': False},
                 'at_flux': {'log': False, 'eval': False},
                 'at_mass': {'log': False, 'eval': False},
                 'aZ_flux': {'log': False, 'eval': False},
                 'aZ_mass': {'log': False, 'eval': False},
                 'am_flux': {'log': False, 'eval': False},
                 'am_mass': {'log': False, 'eval': False},
                 'M2L_r': {'log': True, 'eval': False},
                 'Mcor_fib': {'log': False, 'eval': False},
                 'Mcor_gal': {'log': False, 'eval': False},
                 'z': {'log': False, 'eval': False},
                 'N2Ha': {'log': True, 'eval': True, 'ratio': [['F_6584'], ['F_6563']]},
                 'O3Hb': {'log': True, 'eval': True, 'ratio': [['F_5007'], ['F_4861']]},
                 'HaHb': {'log': True, 'eval': True, 'ratio': [['F_6563'], ['F_4861']]},
                 'O2Hb': {'log': True, 'eval': True, 'ratio': [['F_3727'], ['F_4861']]},
                 'O3N2': {'log': True, 'eval': True, 'ratio': [['F_5007'], ['F_6584']]}}
#                 'S2Ha': {'log': True, 'eval': True, 'ratio': [['F_6716', 'F_6731'], ['F_6563']] } }