'''
Created on Nov 13, 2012

@author: william
'''

import h5py

class Chi2(object):
    '''
    Loads files generated by scripts.chi2fit
    '''

    def __init__(self, filename):
        self._F_ = h5py.File(filename, mode='r')
        self.z = self._F_.attrs['z']
        self.ifile = self._F_.attrs['ifile']
        self.lib = self._F_.attrs['lib'].split('/')[-1] #FIXME:
    
    def list_paths(self):
        paths = []
        for filt in self._F_.keys():
            for ccd in self._F_[filt].keys():
                paths.append('/%s/%s' % (filt, ccd))
        return paths
    
    def get_path(self, path):
        self.n_ds = self._F_.get('%s/n' % path)
        self.chi2_ds = self._F_.get('%s/chi2' % path)
        self.s_ds = self._F_.get('%s/s' % path)