'''
Created on Nov 20, 2012

@author: william
'''

import h5py

class Summaries(object):
    '''
    Loads files generated by scripts.simul_summaries
    '''

    def __init__(self, filename):
        self._F_ = h5py.File(filename, mode='r')
        self.z = self._F_.attrs['z']
        self.ifile = self._F_.attrs['ifile']
        self.lib = self._F_.attrs['lib'].split('/')[-1] #FIXME:
        self.f_L = self._F_.get('/f_L').value
        self.properties = self._F_.get('/property_labels').value
    
    def list_paths(self):
        paths = []
        for filt in self._F_.keys():
            if filt not in ('f_L', 'property_labels'):
                for ccd in self._F_[filt].keys():
                    paths.append('/%s/%s' % (filt, ccd))
        return paths
    
    def get_path(self, path):
        self.path = path
        
    def __getattr__(self,name):
        self.__dict__[name] = self._F_.get('%s/%s' % (self.path, name))
        return self.__dict__[name]
        