'''
Created on Feb 23, 2012

@author: william
'''

from bgpe.io.readfilterset import readfilterset

class starlight2photo(object):
    '''
        This class is used to convert STARLIGHT (http://www.starlight.ufsc.br)
        output files to appropriate filter curve responses and redshift.
          It uses a HDF5 database generated by starlight_hdf5convert.py
    '''

    def __init__(self):
        self.filterfile = '/Users/william/mestrado/Simulations/Alhambra_23.filter'
    
    def db_open(self):
        pass
    
    def db_close(self):
        pass
    
    def read_filter(self):
        '''
        Reads the filterfile and stores on self.filter
        '''
        ReadFilterSetObj = readfilterset()
        ReadFilterSetObj.filterfile = self.filterfile
        ReadFilterSetObj.read()
        self.filter = ReadFilterSetObj.filter 
    
    def read_obs(self):
        pass
    
    def read_syn(self):
        pass
        
    def convert(self, filterset, arq_obs, arq_syn):
        pass
        